[project]
name = "ai-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Omar Farooq", email = "omar.farooq1708@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ai-check = "ai_check:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
